version: "3.8"

services:
  baserow-connector:
    build:
      context: ./baserow-connector-service
    ports:
      - "8080:8080"
    container_name: baserow-connector-container

  sendgrid-connector:
    build:
      context: ./sendgrid-connector-service
    ports:
      - "8081:8081"
    container_name: sendgrid-connector-container

  pdf-connector:
    build:
      context: ./pdf-connector-service
    ports:
      - "8082:8082"
    container_name: pdf-connector-container
