name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push fp-baserow-connector-service image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fp-baserow-connector-service:latest ./baserow-connector-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fp-baserow-connector-service:latest

      - name: Build and push fp-sendgrid-connector-service image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fp-sendgrid-connector-service:latest ./sendgrid-connector-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fp-sendgrid-connector-service:latest

      - name: Build and push fp-pdf-connector-service image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fp-pdf-connector-service:latest ./pdf-connector-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fp-pdf-connector-service:latest
